name: adopte_1_candidat
description: "Unleash your soft skills to find a new job!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.2
  flutter_svg: ^1.0.0
  percent_indicator: ^4.2.2
  flutter_tags: ^1.0.0-nullsafety.1
  path_provider: ^2.0.2
  dotted_border: ^2.0.0
  chat_bubbles: ^1.6.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - lib/redundancy/data.json
    - assets/animation/
    - assets/companyImage/
    - assets/fonts/
    - assets/iconProfile/
    - assets/icons/
    - assets/img/
    - lib/redundancy/data.json
  
  fonts:
    - family: Didot
      fonts:
        - asset: assets/fonts/Didot.otf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/img/favicon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/favicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img/favicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/favicon.png"